In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, ConfusionMatrixDisplay
import pickle
from sklearn.neighbors import KNeighborsClassifier

In [2]:
file_path = 'Data/data.txt'

# K Nearest Neighbors Confusion Matrix

In [24]:
features = []
st_x = StandardScaler()

In [35]:
def KNN(file_path):
    data= pd.read_csv(file_path)
    x=data[features]
    y=data.Solution
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.35, random_state=10)
    x_train = st_x.fit_transform(x_train)
    x_test = st_x.transform(x_test)
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(x_train, y_train)
    predict_y = classifier.predict(x_test)
    cm = confusion_matrix(y_test, predict_y)
    print(cm)
    print('Accuracy Score :',accuracy_score(y_test,predict_y))
    print('Report :')
    print(classification_report(y_test, predict_y))
    pcts = []
    for i in range(len(cm)):
        total = sum(cm[i])
        pcts.append([])
        for j in range(len(cm[i])):
            val = cm[i][j]*100/total
            pcts[i].append(round(val,2))
    print(pcts)
    #save_file4 = 'Models/BEST/New Calibration Solutions KNN.sav'
    #pickle.dump(classifier, open(save_file4,'wb'))

In [40]:
KNN('data_file.txt')

[[14026    94   172   718    79]
 [   60   455     0     0     0]
 [  212     0  1897     0     2]
 [  724     0     0  3561     0]
 [   26     0     0     0   211]]
Accuracy Score : 0.9061474119710392
Report :
              precision    recall  f1-score   support

  Background       0.93      0.93      0.93     15089
         Cal       0.83      0.88      0.86       515
 Conf. Check       0.92      0.90      0.91      2111
      Wet_BG       0.83      0.83      0.83      4285
          YG       0.72      0.89      0.80       237

    accuracy                           0.91     22237
   macro avg       0.85      0.89      0.86     22237
weighted avg       0.91      0.91      0.91     22237

[[92.96, 0.62, 1.14, 4.76, 0.52], [11.65, 88.35, 0.0, 0.0, 0.0], [10.04, 0.0, 89.86, 0.0, 0.09], [16.9, 0.0, 0.0, 83.1, 0.0], [10.97, 0.0, 0.0, 0.0, 89.03]]


In [ ]:
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classifier.classes_)
disp.plot()