In [6]:
from sklearn.svm import SVC
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import BaggingClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, ConfusionMatrixDisplay
import pickle
from sklearn.multiclass import OneVsRestClassifier

In [23]:
features = []
data= pd.read_csv('data_file.txt')
y = data['Solution']
X = data[features]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=10,stratify=y)

In [24]:
%%time
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

CPU times: user 15.2 ms, sys: 3 µs, total: 15.2 ms
Wall time: 13.7 ms


In [25]:
classifier = SVC(kernel = 'rbf', probability = True, random_state = 0)

In [26]:
classifier1 = classifier.fit(X_train, y_train)

In [27]:
save_file= 'save_path_SVM.sav'
pickle.dump(classifier1, open(save_file,'wb'))

In [12]:
%%time
predicted= classifier1.predict(X_test)
cm = confusion_matrix(y_test, predicted, labels=classifier1.classes_)
print(classifier1.classes_)
print('Confusion Matrix :')
print(cm)
print('Accuracy Score :',accuracy_score(y_test,predicted))
print('Report :')
print(classification_report(y_test, predicted))
pcts = []
for i in range(len(cm)):
    total = sum(cm[i])
    pcts.append([])
    for j in range(len(cm[i])):
        val = cm[i][j]*100/total
        pcts[i].append(round(val,2))
print(pcts)

['Background' 'Cal. Soln' 'Conf. Check' 'EH' 'Wet_BG' 'YG. Soln']
Confusion Matrix :
[[40851    83   146  4696   396    56]
 [  115   351     0     0     0     0]
 [  434     0  1362     0     0     2]
 [ 3264     0     0 16863     3     0]
 [  922     0     0   542  2110     0]
 [   59     0     2     0     0   139]]
Accuracy Score : 0.8519255207470026
Report :
              precision    recall  f1-score   support

  Background       0.89      0.88      0.89     46228
   Cal. Soln       0.81      0.75      0.78       466
 Conf. Check       0.90      0.76      0.82      1798
          EH       0.76      0.84      0.80     20130
      Wet_BG       0.84      0.59      0.69      3574
    YG. Soln       0.71      0.69      0.70       200

    accuracy                           0.85     72396
   macro avg       0.82      0.75      0.78     72396
weighted avg       0.85      0.85      0.85     72396

[[88.37, 0.18, 0.32, 10.16, 0.86, 0.12], [24.68, 75.32, 0.0, 0.0, 0.0, 0.0], [24.14, 0.0, 75

In [17]:
%%time
predicted= classifier1.predict(X_test)
cm = confusion_matrix(y_test, predicted, labels=classifier1.classes_)
print(classifier1.classes_)
print('Confusion Matrix :')
print(cm)
print('Accuracy Score :',accuracy_score(y_test,predicted))
print('Report :')
print(classification_report(y_test, predicted))
pcts = []
for i in range(len(cm)):
    total = sum(cm[i])
    pcts.append([])
    for j in range(len(cm[i])):
        val = cm[i][j]*100/total
        pcts[i].append(round(val,2))
print(pcts)

['Background' 'Cal' 'Conf. Check' 'Wet_BG' 'YG']
Confusion Matrix :
[[12100   108   139   597    78]
 [  106   360     0     0     0]
 [  323     0  1473     0     2]
 [  634     0     0  2940     0]
 [   54     0     0     0   146]]
Accuracy Score : 0.8929171038824764
Report :
              precision    recall  f1-score   support

  Background       0.92      0.93      0.92     13022
         Cal       0.77      0.77      0.77       466
 Conf. Check       0.91      0.82      0.86      1798
      Wet_BG       0.83      0.82      0.83      3574
          YG       0.65      0.73      0.69       200

    accuracy                           0.89     19060
   macro avg       0.82      0.81      0.81     19060
weighted avg       0.89      0.89      0.89     19060

[[92.92, 0.83, 1.07, 4.58, 0.6], [22.75, 77.25, 0.0, 0.0, 0.0], [17.96, 0.0, 81.92, 0.0, 0.11], [17.74, 0.0, 0.0, 82.26, 0.0], [27.0, 0.0, 0.0, 0.0, 73.0]]
CPU times: user 11.5 s, sys: 0 ns, total: 11.5 s
Wall time: 11.5 s


# proability true

In [ ]:
def CM(file_name, kernal_type):
    features = []
    data= pd.read_csv(file_name)
    y = data['Solution']
    X = data[features]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=10,stratify=y)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    classifier = SVC(kernel = kernal_type, probability = True, random_state = 0)
    classifier1 = classifier.fit(X_train, y_train)
    predicted= classifier1.predict(X_test)
    cm = confusion_matrix(y_test, predicted, labels=classifier1.classes_)
    print(classifier1.classes_)
    print('Confusion Matrix :')
    print(cm)
    print('Accuracy Score :',accuracy_score(y_test,predicted))
    print('Report :')
    print(classification_report(y_test, predicted))
    pcts = []
    for i in range(len(cm)):
        total = sum(cm[i])
        pcts.append([])
        for j in range(len(cm[i])):
            val = cm[i][j]*100/total
            pcts[i].append(round(val,2))
    print(pcts)

In [ ]:
CM('data_file.txt', 'rbf')

# Origial SVM

In [ ]:
def CM(file_name, kernal_type):
    features = []
    data= pd.read_csv(file_name)
    y = data['Solution']
    X = data[features]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=10,stratify=y)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    classifier = SVC(kernel = kernal_type, random_state = 0)
    classifier1 = classifier.fit(X_train, y_train)
    predicted= classifier1.predict(X_test)
    cm = confusion_matrix(y_test, predicted, labels=classifier1.classes_)
    print(classifier1.classes_)
    print('Confusion Matrix :')
    print(cm)
    print('Accuracy Score :',accuracy_score(y_test,predicted))
    print('Report :')
    print(classification_report(y_test, predicted))
    pcts = []
    for i in range(len(cm)):
        total = sum(cm[i])
        pcts.append([])
        for j in range(len(cm[i])):
            val = cm[i][j]*100/total
            pcts[i].append(round(val,2))
    print(pcts)

In [ ]:
CM('data_file.txt', 'rbf')